server:
  port: 80
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yankee.democratic@gmail.com
    password: 47913555
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: 4791355pDa
  jpa:
    hibernate:
      ddl-auto: update
auction:
  pretender:
    subject: "Вы выиграли аукцион"
    text: "Теперь выигранная экипировка будет отправлена к вам. Свяжитесь с организатором аукциона в случае возникновения
    вопросов"
  owner:
    subject: "Аукцион завершен"
    text: "Теперь вы должны отправить победителю обозначенные в аукционе вещи. Свяжитесь с ним в ближайшее время"
wishlist:
  added:
    notification:
      subject: "Вещи из вашего списка желаемого появились в продаже"
      before: "Речь идет о следующей экипировке, подходящей под ваши фильтры:"
      after: "Не упустите возможность связаться с продавцами"
order:
  seller:
    subject: ""
    text: ""
logging:
  level:
    org.springframework.security.web.access: DEBUG
