spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: yankee.democratic@gmail.com
    password: 47913555
    properties:
      mail:
        smtp:
          auth: true
          starttls: true
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 4791355pDa
